version: "2"
services:
  proxy:
    image: nginx:stable
    # port:
    #   - "80"
    labels:
      io.rancher.sidekicks: provt,proxy-conf
    volumes_from:
      - proxy-conf
      - provt
  proxy-conf:
    image: samoyeds/provt-nginx-conf:0.1.0
    entrypoint: /bin/true
    labels:
      io.rancher.container.start_once: "true"
    volumes:
      - /etc/nginx/nginx.conf
  provt:
    image: samoyeds/provt:0.1.0
    entrypoint: /bin/true
    labels:
      io.rancher.container.start_once: "true"
    volumes:
      - /app

  provt-server:
    image: samoyeds/provt-server:0.1.0
    environment:
      - MONGO_URI=mongodb://mongo/provt

  mongo:
    image: mongo:3.4
    labels:
      io.racher.sidekicks: mongo-data
    volumes_from:
      - mongo-data
  mongo-data:
    image: busybox
    entrypoint: /bin/true
    labels:
      io.rancher.container.start_once: "true"
    volumes:
      - /data/db

  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    labels:
      io.rancher.container.create_agent: "true"
      io.rancher.container.agent.role: environment
    environment:
      - "API_VERSION=Production"
      - "CERT_NAME=${PROVT_DOMAIN}"
      - "DNS_RESOLVERS=8.8.8.8:53,8.8.4.4:53"
      - "DOMAINS=${PROVT_DOMAIN}"
      - "EMAIL=${PROVT_EMAIL}"
      - "EULA=Yes"
      - "PROVIDER=HTTP"
      - "PUBLIC_KEY_TYPE=RSA-2048"
      - "RENEWAL_PERIOD_DAYS=20"
      - "RENEWAL_TIME=12"
    volumes:
      - /var/lib/rancher:/var/lib/rancher
